[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = [
  "cd frontend && npm run build && cd .."
]

[start]
cmd = "cd backend && npm start"
